#!/usr/bin/env bash
# Display subdomain DNS record info using dig

domain="$1"
subdomain="$2"

print_subdomain_info() {
	local sub="$1"
	local result
	result=$(dig "$sub.$domain" | awk '/^;; ANSWER SECTION:/{getline; print $4, $5}')
	local record_type
	local destination
	record_type=$(echo $result | awk '{print $1}')
	destination=$(echo $result | awk '{print $2}')
	echo "The subdomain $sub is a $record_type record and points to $destination"
}

if [ -n "$subdomain" ]; then
	print_subdomain_info "$subdomain"
else
	for sub in www lb-01 web-01 web-02; do
		print_subdomain_info "$sub"
	done
fi
