#!/usr/bin/env bash
# Configure Nginx to listen on port 80 and restart it.

rm  /etc/nginx/sites-enabled/default
ln -s  /etc/nginx/sites-available/default /etc/nginx/sites-enabled
sudo service nginx restart
