#!/usr/bin/env bash
# Configures nginx to have a custom 404 page

apt-get update -y
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Add redirect rule
sed -i '/server_name _;/a\\tlocation /redirect_me { return 301 https://www.w3schools.com/python; }' /etc/nginx/sites-available/default

# Add custom 404 error page
sed -i '/server_name _;/a\\terror_page 404 /404.html;' /etc/nginx/sites-available/default

service nginx start
service nginx restart

exit 0
